let arrLang = {
    "english": {
        "WELCOME": "WELCOME",
        "GO-BACK": "Go Back",
        "to_start_a_test": "To start a test, enter your email address and the test PIN",
        "Email": "Email",
        "TEST-PIN": "Test PIN",
        "Start": "Start",
        "IMPORTANT": "IMPORTANT",
        "you_will_now": "You will now see instructions on how to prepare for the test.",
        "payment_is_conditional": "Payment is <b>conditional</b> upon following these instructions.",
        "please_note_that": "Please note that you will not have a second chance to submit a test.",
        "i_understand_that": "I understand that I may not receive payment if I do not follow the next instructions.",
        "eliminate_distractions": "Eliminate distractions",
        "make_sure_that": "Make sure that there are no noises in the room and that you will not be interrupted for the next 10-20 minutes.",
        "NEXT": "NEXT",
        "face_your_webcam": "Face your webcam",
        "make_sure_that_your": "Make sure that your webcam is in front of you, and not to the side.",
        "close_other_open_tabs": "Close other open tabs",
        "close_any_other": "Close any other open tabs in your browser window.",
        "start_recording": "Start Recording",
        "start_the_recording": "Start the recording",
        "when_youre_ready": "When you’re ready, press ‘Start Recording’ and select <b>‘Entire Screen’ or ‘Application Window’</b>",
        "change_your_face": "Change your face on the square",
        "make_sure_you_can": "Make sure you can hold this position during the test.",
        "please_follow_the": "Please follow the circle with your eyes.",
        "start_calibration": "Start Calibration",
        "almost_ready": "Almost Ready!",
        "you_will_now_complete": "You will now complete a test on a different website.",
        "the_webste_will": "The website will open on a new tab.",
        "your_task": "Your Task",
        "once_on_the_website": "Once on the website, please do the following: ",
        "end_the_test_": "End the test?",
        "did_you_complete": "Did you complete the task?",
        "if_youre_not": "If you’re not done yet, press ‘Cancel’ and then select the test tab on your browser (this is the tab that opened after you started the test)",
        "CANCEL": "CANCEL",
        "end_the_test": "END THE TEST",
        "we_will_now": "We will now ask you to answer a few short questions. ",
        "please_answer_the": "Please answer the question below",
        "extremely_unlikely": "Extremely Unlikely",
        "extremely_likely": "Extremely Likely",
        "custom_questions": "Custom Questions",
        "tell_us_about": "Tell us about yourself",
        "gender": "Gender",
        "male": "Male",
        "female": "Female",
        "prefer_not_to_say": "Prefer no to say",
        "location": "Location",
        "yearly_income": "Yearly income (excluding taxes)",
        "no_selection": "No Selection",
        "no_income": "No Income",
        "the_test_has_ended": "The test has ended.",
        "did_you_experience": "Did you experience any difficulties with this test?",
        "overall_this_task": "Overall, this task was?",
        "very_difficult": "Very Difficult",
        "very_easy": "Very Easy",
        "give_us_a_second": "Give us a second...",
        "please_wait_while_we": "Please wait while we upload your test files.",
        "screen_recording_progress": "Screen Recording progress:",
        "camera_recording_progress": "Camera Recording progress:",
        "please_do_not": "Please <b>do not</b> close your browser window before the upload is done.",
        "doing_so_may": "Doing so may lead to losing your test data, and not receiving payment for this test.",
        "if_the_videos": "If the videos are not uploading we request you download the videos onto your computer (press the button below) and contact us (particpants@cubehx.com) so you can send them manually to us.",
        "download_videos": "Download Videos",
        "you_may_now_close": "You may now close your browser window or tab.",
    },
    "french": {
        "WELCOME": "BIENVENUE",
        "GO-BACK": "Retour",
        "to_start_a_test": "Pour démarrer le test, veuillez saisir le code PIN du test",
        "Email": "Adresse courriel",
        "TEST-PIN": "Code PIN du test",
        "Start": "Démarrer",
        "IMPORTANT": "IMPORTANT",
        "you_will_now": "Vous verrez maintenant des instructions sur comment vous préparer au test.",
        "payment_is_conditional": "Le paiement est <b>conditionnel</b> au respect de ces instructions.",
        "please_note_that": "Veuillez noter que vous ne pourrez pas soumettre le test une seconde foi.",
        "i_understand_that": "Je comprends que je pourrais ne pas recevoir de paiement si je ne suis pas les instructions suivantes.",
        "eliminate_distractions": "Éliminer toute distraction",
        "make_sure_that": "Assurez-vous d’être dans une pièce calme et de ne pas être  interrompu pendant les 10 à 20 prochaines minutes.",
        "NEXT": "Suivant",
        "face_your_webcam": "Fait face à votre caméra",
        "make_sure_that_your": "Assurez-vous que votre caméra se trouve devant vous et non sur le côté.",
        "close_other_open_tabs": "Fermer les autres onglets ouverts",
        "close_any_other": "Fermer les autres onglets ouverts dans la fenêtre de votre navigateur.",
        "start_recording": "Démarrer l’enregistrement",
        "start_the_recording": "Démarrer les enregistrements",
        "when_youre_ready": "Quand vous êtes prêt, appuyer sur ‘Démarrer l’enregistrement’ et sélectionner <b>‘Écran entier’ ou ‘Fenêtre d’application’</b>",
        "change_your_face": "Positionnez votre visage dans le carré",
        "make_sure_you_can": "Assurez-vous de pouvoir maintenir cette position pendant le test.",
        "please_follow_the": "Veuillez suivre des yeux le cercle.",
        "start_calibration": "Démarrer le calibrage",
        "almost_ready": "Vous êtes presque prêt!",
        "you_will_now_complete": "Vous allez maintenant compléter un test sur un autre site Web.",
        "the_webste_will": "Le site Web s’ouvrira dans un autre onglet.",
        "your_task": "Votre tâche",
        "once_on_the_website": "Une fois sur le site Web, veuillez procéder comme suit: ",
        "end_the_test_": "Terminer le test?",
        "did_you_complete": "Avez-vous terminé la tâche?",
        "if_youre_not": "Si vous n’avez pas encore terminé, appuyer sur ‘Annuler’ puis sélectionnez l’onglet de test sur votre navigateur (c’est l’onglet qui s’est ouvert après avoir commencé le test)",
        "CANCEL": "ANNULER",
        "end_the_test": "TERMINER LE TEST",
        "we_will_now": "Nous allons maintenant vous demander de répondre à quelques brèves questions. ",
        "please_answer_the": "Veuillez répondre à la question ci-dessous",
        "extremely_unlikely": "Extrêmement Improbable",
        "extremely_likely": "Extrêmement Probable",
        "custom_questions": "Questions Personnalisées",
        "tell_us_about": "Dites-nous en plus sur vous",
        "gender": "Genre",
        "male": "Homme",
        "female": "Femme",
        "prefer_not_to_say": "Je ne préfère pas répondre",
        "location": "Emplacement",
        "yearly_income": "Revenu annuel avant impôts",
        "no_selection": "Aucune sélection",
        "no_income": "Aucun revenu",
        "the_test_has_ended": "Le test est terminé.",
        "did_you_experience": "Avez-vous rencontré des difficultés avec ce test?",
        "overall_this_task": "Dans l’ensemble, cette tâche était?",
        "very_difficult": "Très Difficile",
        "very_easy": "Très Facile",
        "give_us_a_second": "Donnez-nous une seconde...",
        "please_wait_while_we": "Veuillez patienter pendant que nous téléchargeons vos fichiers de test.",
        "screen_recording_progress": "Progression de l’enregistrement de l’écran:",
        "camera_recording_progress": "Progression de l’enregistrement de la caméra:",
        "please_do_not": "Veuillez <b>ne pas</b> fermer la fenêtre de votre navigateur avant la fin du téléchargement.",
        "doing_so_may": "Cela peut entraîner la perte de vos données de test et ne pas recevoir de paiement pour ce test.",
        "if_the_videos": "Si les vidéos ne sont pas téléchargées, nous vous demandons de télécharger les vidéos sur votre ordinateur (appuyez sur le bouton ci-dessous) et de nous contacter (particpants@cubehx.com) afin que vous puissiez nous les envoyer manuellement.",
        "download_videos": "Télécharger des vidéos",
        "you_may_now_close": "Vous pouvez maintenant fermer la fenêtre ou l'onglet de votre navigateur.",
    }
};
